export const Cardata = [
    {
        id : '1',
        title : 'TESLA MALIBU',
        image : 'https://stimg.cardekho.com/images/carexteriorimages/930x620/Tesla/Model-3/5251/1693556345148/front-left-side-47.jpg',
        price : '$ 80',
        icon : 'fa-solid fa-car',
        model : 'Model 3',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '2',
        title : 'VW POLO',
        image : 'https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/volkswagen-polo_1.jpg?itok=xQcc-xtl',
        price : '$ 40',
        icon : 'fa-solid fa-car',
        model : '2012-2019',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '3',
        title : 'VW GOLF VII',
        image : 'https://images.caradisiac.com/images/8/6/5/7/88657/S1-Futur-VW-Golf-R-elle-est-la-300158.jpg',
        price : '$ 50',
        icon : 'fa-solid fa-car',
        model : '2013-2018',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '4',
        title : 'BMW 1-SERIES',
        image : 'https://s1.cdn.autoevolution.com/images/gallery/BMW-1-Series--F20--LCI-6006_10.jpg',
        price : '$ 80',
        icon : 'fa-solid fa-car',
        model : '2013-2018',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '5',
        title : 'AUDI A3',
        image : 'https://www.turbo.fr/sites/default/files/2020-03/2021-audi-a3-sportback-23_0.jpg',
        price : '$ 65',
        icon : 'fa-solid fa-car',
        model : '2016-2021',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '6',
        title : 'PORSCHE Cayenne',
        image : 'https://media.ed.edmunds-media.com/porsche/cayenne/2024/oem/2024_porsche_cayenne_4dr-suv_base_fq_oem_1_1600.jpg',
        price :  '$ 150',
        icon : 'fa-solid fa-car',
        model : '2018-2021',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '7',
        title : 'MERCEDES GLE',
        image : 'https://media.autoweek.nl/m/norygbfbpfvc_800.jpg',
        price : '$ 200',
        icon : 'fa-solid fa-car',
        model : '2012-2019',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '8',
        title : 'BMW X5',
        image : 'https://cdn.motor1.com/images/mgl/Kbb6mQ/s3/redesigned-bmw-x5-m-unofficial-renderings.jpg',
        price : '$ 300',
        icon : 'fa-solid fa-car',
        model : '2022-2023',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '9',
        title : 'BMW X6',
        image : 'https://hips.hearstapps.com/hmg-prod/images/p90495559-1677001917.jpg?crop=0.721xw:0.540xh;0.194xw,0.367xh&resize=640:*',
        price : '$ 365',
        icon : 'fa-solid fa-car',
        model : '2016-2021',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '10',
        title : 'JAGUAR F-PACE',
        image : 'https://hips.hearstapps.com/hmg-prod/images/2021-jaguar-f-pace-s-p400-152-1630522615.jpg?crop=0.753xw:0.564xh;0.228xw,0.381xh&resize=1200:*',
        price : '$ 280',
        icon : 'fa-solid fa-car',
        model : '2013-2018',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '11',
        title : 'MERCEDES AMG GT63S',
        image : 'https://car-images.bauersecure.com/wp-images/13349/80-mercedes-amg-gt63-e-performance-hero.jpg',
        price : '$ 265',
        icon : 'fa-solid fa-car',
        model : '2016-2021',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
    {
        id : '12',
        title : 'VW TIGUAN',
        image : 'https://www.motortrend.com/uploads/2022/10/2023-Volkswagen-Tiguan-SE-R-Black-exterior-3.jpg',
        price :  '$ 150',
        icon : 'fa-solid fa-car',
        model : '2018-2021',
        gearbox : 'fa-solid fa-gear',
        titlegearbox :'Automatic',
        liter : 'fa-solid fa-gas-pump',
        titleliter : '4.5L/100Km',
    },
]